### ISSUE TITLE
emit and listen to events on rabbitmq

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1035]
OBS is meant to emit events on rabbitmq. Some of our bots should react on that and potentially also emit events themselves. For example TTM could emit when it's moving a snapshot to testing and when releasing it.

**Comment by coolo** [comment]
'OBS is meant to emit events on rabbitmq' - yeah, to the product owner. It's meant to be since january

**Comment by jberry-suse** [comment]
Presumably this is related to the building against snapshot email thread. Seems like it would make sense to tweak the workflow a bit, perhaps add a new repo that mirrors what is published, since all devel projects suffer from the same problem of building and publishing against snapshots they may never be released. Could still have the 2 hour delay to give them a head start or whatever is desired, but it seems like there should be a repo that accurately represents TW.

**Comment by DimStar77** [comment]
The /snapshot repo gas been following the releases as passed by ttm for almost two years now... The only issues are delete requests impacting /snapshot immediatly. That mail thread cn't be related... It doesn't matter how ibs gets the signal to sync, as long as pkg deletes impact everything (pending pogress issue, max is looking into this already)

**Comment by jberry-suse** [comment]
IBS has the identical issue that all devel projects do. It works, but can clearly cause issues. Rather than make another one off fix it seems more prudent to really fix it.

**Comment by coolo** [comment]
The only thing that helps against delete requests is moving the snapshot repo out of openSUSE:Factory

**Comment by jberry-suse** [comment]
This would probably be the preferred route for something like #1029 which could simply run anytime a new snapshot is accepted or published.

**Comment by coolo** [comment]
we already listen - and TTM also emits. So I close this one. Moving /snapshot out of openSUSE:Factory is on TODO, but blocked atm
