### ISSUE TITLE
cleanup_rings: fails to work on Leap

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1278]
cleanup_rings does not work for Leap 15.0 at the moment. One reason is the switch from _product to 000product but the rest is a mystery to me

**Comment by jberry-suse** [comment]
It's one my favorite code comments:

https://github.com/openSUSE/osc-plugin-factory/blob/3b99a9d434c0d142996d94879ba47f94702a5178/osclib/cleanup_rings.py#L93-L94

This bit seems a bit odd, I'd have to investigate further.

The product builder changes need to be reflect in `Test-DVD` and similar lookups. Would likely make sense to describe these things in common location (similar to `StagingAPI` `c*` variables) and use elsewhere. The same for the various tools that try to find source packages in various SLE/update/GA projects and such rather than updating all these tools every time anything changes.

**Comment by lkocman** [comment]
Without checking git blame ... that totally sounds like the issue reporter ;-)

**Comment by coolo** [comment]
Looking at the git commit, it seems to generally work - and what was broken in 15.0 is hard to say now
