### ISSUE TITLE
pkglistgen: do_update() skips generating new solv when no updates indicated by bs_mirror 

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1377]
pkglistgen doesn't update the solv file if bs_mirrorfull didn't do anything. Since repochecker also calls bs_mirrorfull it would fool pkglistgen to work on an outdated solv file

**Comment by jberry-suse** [comment]
Related to #1257 in that all caches should be consolidated and likely all use either standard mechanism to know if changed since they last checked (like local cache file) or build hash like `repo_checker` uses.

Presumably, the simplest solution would be to simply drop `repo_update` check in:

https://github.com/openSUSE/osc-plugin-factory/blob/40c4c14db52af9b7fac403aa0ee3f0c62980d86f/pkglistgen.py#L738-L746

**Comment by jberry-suse** [comment]
Of the 4 places that use this cache `pkglistgen.py` is the only one to depend on the script output.

**Comment by jberry-suse** [comment]
Example of this occurring https://bugzilla.opensuse.org/show_bug.cgi?id=1109134.
