### ISSUE TITLE
NonFree workflow: repo-checker refuses to check

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#1384]
Since recently, submissions submitted to openSUSE:Factory:NonFree are passing a staging project, as they should.

repo-checker is added as a reviewer there, to ensure minimal quality.

Unfortunately, repo-checker claims the submissions would not be staged, as the target project is does not match the prefix of the staging project

```
> repo_checker   --debug  --dry --skip-cycle id 571416
[D] 571416: not staged
[D] requests: 1 skipped, 0 queued
```

571416 is staged in adi:9

**Comment by jberry-suse** [comment]
This was the whole point of #1247 to which I had given thought and was the reason for creating that issue.

**Comment by DimStar77** [comment]
Let's merge the info there then; I merely opened a new issue since stagign adi since recently catches those submissions and stages them. I don't mind to still ignore them of course

**Comment by jberry-suse** [comment]
I need to get back to this, but I have been wondering why `:NonFree` requests are even staged in the oss area. Why not stage them in `:NonFree:Staging:adi:123`. Then the same `:adi` -> `:Staging` link could exist to allow for staging settings instead of the special `:NonFree` one added in #1379. I'd have to see which one the code prefers, but from the places that needed adapting for `:NonFree` it really just questions why we treat them as targeting the same project for staging when in every other way they are not.

**Comment by DimStar77** [comment]
During checkin, NonFree is also treated as part of the main repo: the requests are being checked in together as part of the snapshot, not as part of a 2nd staging accept call

**Comment by jberry-suse** [comment]
Yeah, I understand that. It is being treated as both which is not ideal and creates this problem.

**Comment by jberry-suse** [comment]
@DimStar77 perhaps add the repo-checker review to the next NonFree request you see or just add to project.
