### ISSUE TITLE
repo_checker: i686 packages not considered

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/openSUSE-release-tools#1481]
on SLE15, we have the following error now:

i586
install check & file conflicts
can't install MozillaFirefox-branding-SLE-59-5.1.i586:
  nothing provides MozillaFirefox >= 59 needed by MozillaFirefox-branding-SLE-59-5.1.i586
  nothing provides MozillaFirefox < 60 needed by MozillaFirefox-branding-SLE-59-5.1.i586

MozillaFirefox is a i686 package now, not a i586 package, which seems to cause a problem for repo-checker

**Comment by jberry-suse** [comment]
Indeed.

**Comment by jberry-suse** [comment]
This is one of the screwy bits of how `i686` is implemented. If one asks OBS for the binaries built for `openSUSE:Factory/standard/i586` the list includes:

```
MozillaFirefox-58.0.2-1.2.src
MozillaFirefox-debuginfo-58.0.2-1.2.i686
MozillaFirefox-branding-openSUSE-45-4.1.i586
MozillaFirefox-58.0.2-1.2.i686
MozillaFirefox-branding-openSUSE-45-4.1.src
MozillaFirefox-buildsymbols-58.0.2-1.2.i686
MozillaFirefox-translations-other-58.0.2-1.2.i686
MozillaFirefox-translations-common-58.0.2-1.2.i686
MozillaFirefox-devel-58.0.2-1.2.i686
MozillaFirefox-debugsource-58.0.2-1.2.i686
MozillaFirefox-branding-upstream-58.0.2-1.2.i686
```

Note the `i686`, but since the binaries are not placed in the `i586` directory in repository tree `bs_mirrorfull` does not download them. Downloading them thus requires special casing for the `i586` architecture and handling an extra directory where there normally is one.

**Comment by jberry-suse** [comment]
If the `i686` binaries are simply copied into the `i586` directory after mirroring `bs_mirrorfull` will nuke them next time that `i586` directory is mirrored. `repo_checker.pl`, even after heavy modification to allow for stacking all the staging projects assumes the base layer is a single directory whereas two directories are now needed at all levels.

**Comment by jberry-suse** [comment]
Estimation of changes required:

- `repo_checker.pl` thus would require `-r` to be expanded to support > 1 directory.
- `repo_checker.py:mirror()` changed to return array of directories and calling locations changed
- `repo_checker.py:install_check()` modified to know which directories are project base and can be ignored. previously this was simple the first one in stack, but now will likely need another arch check and look for 2
- wrap logic to allow for non-existent `i686` directory

**Comment by jberry-suse** [comment]
My $0.02, OBS should put them in the directory for which they are used as `i686` functions as a revision of `i586`. This assumes zypper and createrepo do not have a problem with this. Otherwise this remains inconsistent with the API.

Obviously, repo-checker can be changed as well, but this just seems messy.

**Comment by coolo** [comment]
For SLE I would prefer an option to ignore all of i586 - we don't do any product with it (same for leap), so any inconsistencies not found by regular staging are completely uninteresting.

**Comment by fcrozat** [comment]
Changing OBS setup is not really an option..

**Comment by adrianschroeter** [comment]
which repo you speak about? the :full aka _repository ?
It would be just one ExportFilter line in prjconf....

**Comment by jberry-suse** [comment]
> For SLE I would prefer an option to ignore all of i586 - we don't do any product with it (same for leap), so any inconsistencies not found by regular staging are completely uninteresting.

@coolo Such an option already exists as Leap uses it and so does SLE 15, but should just remove `i586` as it currently reads:

```
repo_checker-arch-whitelist = i586 x86_64
```

> which repo you speak about? the :full aka _repository ?
> It would be just one ExportFilter line in prjconf....

@adrianschroeter I am not sure what `:full:` or `_repository` reference, but the `standard` repo for `openSUSE:Factory` as I noted in `openSUSE:Factory/standard/i586`. For Factory this is still an issue since `i586` is supported. If SLE 15 does not care then the solution there is simpler.

**Comment by jberry-suse** [comment]
@adrianschroeter The two directories present in published repository.

- http://download.opensuse.org/tumbleweed/repo/oss/i686/
- http://download.opensuse.org/tumbleweed/repo/oss/i586/

**Comment by jberry-suse** [comment]
As for `_repository` the API query is `['build', project, repository, arch]`.

**Comment by coolo** [comment]
bs_mirrorfull is called this way as the author knew that the _repository route reads :full directory :)
