### ISSUE TITLE
ReviewBot: runner mode never resets state and caches so memory usage grows

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1511]
For SLE Rudi runs it as review -n 3 - and it grows to 2G rather quickly (in a day or so), exceeding the available memory and crashing as consequence.

**Comment by coolo** [comment]
(I just failed on github UI, no intent to debug that :)

**Comment by jberry-suse** [comment]
The simplest solution being to run it the way the provided service files do.

**Comment by jberry-suse** [comment]
I skimmed through `repo_checker.py` and `ReviewBot.py`, but nothing jumped out. My best guess would be `memoize(session=True)`.

**Comment by lnussel** [comment]
might be also related to libsolv bindings. /me vaguely remembers some explicit del in some older code

**Comment by jberry-suse** [comment]
Would think that would be limited to pkglistgen as repo_checker invokes a separate process to extract rpm metadata and to perform install check.

**Comment by coolo** [comment]
memoize sounds plausible - as the check_source on the same VM leaks also memory, just not as bad. Both start with 30M RSS and check_source was this morning at 400M and repo_checker at 1380M. So a nightly restart might be good enough - if @bugfinder insists on running it as daemon. I'm just worried that the restart leaves the bot in a limbo

**Comment by jberry-suse** [comment]
If we are going to support running as daemon I think we need to modify memoize to expire session data at some interval which likely means we need to add another parameter so the call can specify how long like they do for non-session data.

Short of a compelling use-case I this seems like the lowest possible priority.

I would imagine this is the big one for `repo_checker`.

https://github.com/openSUSE/openSUSE-release-tools/blob/2550cb4240c93b904f09167d662747c4e46f2ba7/osclib/core.py#L123-L151

**Comment by jberry-suse** [comment]
I would also expect to get a fair bit of false results since that is a rather important query to cache.

**Comment by jberry-suse** [comment]
The other potentially relevant source I ran into when working on metrics since it loads GiB worth of data.

https://github.com/openSUSE/openSUSE-release-tools/blob/1730947869cabfbc6949b8894d7afc78766a4653/metrics.py#L79

**Comment by jberry-suse** [comment]
The new code definitely reduces the growth substantially, but there are still lxml issues and likely others.

I modified `repo_checker` run do a minimal set of queries including `package_binary_list()`, but skip the slow external calls and I'm still seeing growth. At least with new code it requeries the build results and such.

Interestingly if I do a run with the following patch the memory increases are reduced significantly.

```diff
diff --git a/osclib/core.py b/osclib/core.py
index 8bf4ba4..1de80a2 100644
--- a/osclib/core.py
+++ b/osclib/core.py
     if package:
         path.append(package)
@@ -149,6 +151,8 @@ def package_binary_list(apiurl, project, repository, arch, package=None, strip_m
             package_binaries.append(binary)
             binary_map[result.group('filename')] = package
 
+    root.clear()
+
     return package_binaries, binary_map
 
 def binary_src_debug(binary):
```

https://gist.github.com/jberry-suse/b7fd4e3fb6608272a492227b97d5458b

This seems to be the same behavior I saw with `metrics.py` in that lxml does not release the memory even after no longer referenced. So to truly get rid of this would need to call `.clear()` all over the place after finished using an XML tree or find a better solution.

Personally, I would suggest we stop using the runner mode since we already have a daemon running that can kick off the process each time.

**Comment by jberry-suse** [comment]
More long-term testing and/or explicit garbage collection calls would be needed to see if this pans out.

**Comment by jberry-suse** [comment]
I can only imagine the confusing output and behavior (like updating whitelist and still having repo-checker complain since it would not see config changes until it crashes and reboots). Given this code is really not designed for this and no benefits I would still recommend not running it this way. I am still rather curious why no feedback prior to this as I can only imagine how this behaved.
