### ISSUE TITLE
factory-source wrongly adds "backports-reviewers" as reviewer

### ISSUE THREAD

**Issue by ismail** [openSUSE/openSUSE-release-tools#1703]
Such an SR is https://build.opensuse.org/request/show/636853 , for Package Hub 12 backports-reviewers must be added as a reviewer but for Package Hub 15 it's not needed (and unwanted).

And for https://build.opensuse.org/project/users/openSUSE:Backports:SLE-15:Update backports-reviewers is not assigned as a reviewer. Compare that to https://build.opensuse.org/project/users/openSUSE:Backports:SLE-12

**Comment by ismail** [comment]
This might be due to the fact that https://build.opensuse.org/project/users/openSUSE:Backports:SLE-15 has backports-reviewers as a reviewer still.

**Comment by andreasstieger** [comment]
Additional info: 

* PH 15 submitted sources do not need to be in Factory, as they follow Leap Maintenance, not Factory.
* We have an auto-importer script that copies maintenance updates from Leap 15.0 to PackageHub for packages (into a new incident).
* A sensible check would be that the Leap 15.0 submission and the PH 15 submission should be source identical

**Comment by jberry-suse** [comment]
`factory-source` is deprecated and would no longer be added as a reviewer by `leaper` and the deprecated `maintbot` (#1664). Was pending confirmation of `leaper` behavior which does not have that simplified logic requiring origin.

The `factory-source` is run with the following command:

```
/usr/local/bin/check_source_in_factory --factory openSUSE:Factory --factory openSUSE:Leap:15.0:Update --factory openSUSE:Leap:15.0 --factory openSUSE:Leap:15.0:Update --factory openSUSE:Leap:15.0 --review-mode=fallback-onfail --fallback-group=backports-reviewers --verbose review
```

Which is causing the addition of `backports-reviewers` since the `factory-source` bot would otherwise decline the submission based on that rule.

Improving the code does not makes given it is deprecated and improvements should focus on `leaper` and the upcoming rewrite. I see a couple paths forward.

1) stop using `maintbot` and fully switch to `leaper` and deal with any necessary changes
2) tweak `factory-source` configuration to have a different fallback-group
3) comment out the logic entirely for the time being

**Comment by andreasstieger** [comment]
A full replacement of maintboot with leaper is not yet possible as leaper implements too many assumptions that do not hold true for the maintenance workflow. But then again, nothing that cannot be fixed.

**Comment by jberry-suse** [comment]
This is a matter of policy, I can make it work however we want. The second two options are both available.

**Comment by andreasstieger** [comment]
For the parts of submissions that contain `openSUSE:Backports:SLE-15:Update` targets:

* Look for a source identical change submitted either in the same maintenance submission or in parallel. (Refer to `openSUSE:Backports:SLE-15:Update/00Meta lookup.yml` for where it would be submitted to, not submitted from.)
* If an identical source change is not found, comment to that effect

**Comment by jberry-suse** [comment]
Alright, so this needs to wait and be part of origin manager as the current logic has been in place quite some-time and is very simplistic surrounding this bit.
