### ISSUE TITLE
origin-manager: don't block on Factory staging

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1904]
In https://build.opensuse.org/request/show/684722 origin-manager sits there and waits for a Factory letter staging to complete since days. There is no need for that slowdown. origin-manager can just ignore Factory staging.

**Comment by jberry-suse** [comment]
Last we talked my understanding was request needed to be in state `new` for acceptance into Leap which is how adi requests can get in before they are accepted into Factory.

Otherwise, it's just a config option what reviews are allowed. By default staging and `repo-checker` reviews are ignored, if we want that back just need to remove the override in `OSRT:OriginConfig`.

https://github.com/openSUSE/openSUSE-release-tools/blob/b7eeea5d9817ca60c2ce76a0bc5a2455eb054561/osclib/origin.py#L36-L39

**Comment by jberry-suse** [comment]
removed the override from `OSRT:OriginConfig`:

```
    # Do not allow any pending reviews (ie. state new).
    pending_submission_allowed_reviews: []
```
