### ISSUE TITLE
repo_checker: put machine readable file in dashboard

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1950]
The repo_checker file in the dashboard isn't really machine friendly. For external notification mechanisms or visualization it would be nice to get that by source package. Looks like repo_checker already does the hard work anyways to post comments so the package_results() function has the right format. How about dumping that one to the dashboard too?

@jberry-suse

**Comment by jberry-suse** [comment]
What is the current state of this as presumably the repo_checker code was broken and then left that way when much was copy-pasted into new tool. I am not sure what the state is at this point as in which tool is being used where.

The repo_checker used to post comments on devel projects. The same technique could be used elsewhere. Otherwise, we're back to needed a structured dump of information which requires a different approach since the tool only had text previous, but perhaps some of that is closer.

**Comment by lnussel** [comment]
AFAIK it's just repo_checker.py that is used still. I think it would make sense to combine build fail reminders with also the install fail information. So maintainers get issues with their packages in a central, uniform way.

**Comment by coolo** [comment]
Repo checker is used for 3 things atm:
- project only mode to calculate whitelist for adi projects
- comments/issues per package
- verifying maintenance incidents on openSUSE

Using the staging-installcheck for incidents sounds possible, would need to look at it in detail (we could have a simple followup script that translates repo checks into reviews).

So dropping the comments, that mostly hit the wrong persons (especially for SLE they are mostly spamming the release managers) and favor a specific mail generated elsewhere based on the 'project only' data sounds like a neat idea to me.

That gives repo_checker.py a single purpose - and makes it possible to refactor the common parts. I didn't dare doing that as I didn't want to break repo_checker.py

**Comment by jberry-suse** [comment]
The IBS setup for SLE does not leave any other options short of directly sending emails. As is typical, long-standing feature request against OBS openSUSE/open-build-service#4590 which makes sense in general give the SLE setup.

> didn't dare doing that as I didn't want to break repo_checker.py

Lets not pretend, the last structural change pertaining to leaking rings broke it quite a bit.

The primary issue here, is we already have the output in a file in the dashboard and no further structure output can be provided short of the larger switch to using python bindings for underlying checks and exposing the data structure, but that is a can of worms documented in other issues.

As such any additional tool that parses the file would need to do what repo_checker is already doing. As such if there are changes to be made it would seem most logical to introduce them to the code already doing it rather than add another piece to the workflow.

**Comment by coolo** [comment]
Even with 4590 implemented, it would be a nightmare to solve with comments. Because you can have broken dependencies in the underlying maintenance update (i.e. provides required by SP0 disappearing in SP1).

But I agree with you, we should switch to python bindings before we pretend to be smart parsing perl output in python.

**Comment by coolo** [comment]
Working on the 9th repo checker rewrite ...

**Comment by coolo** [comment]
done
