### ISSUE TITLE
origin-manager: include pending request info in annotation

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2151]
https://build.opensuse.org/request/show/720688

I can't see whether this package is identical with Factory and has therefore been reviewed by review-team. If it's not identical with a reviewed origin we need reviews.

**Comment by jberry-suse** [comment]
It's coming from the maintenance project for Leap 15.1 and indicates in the description which request it was matching. I'll change this to be a feature request to include the pending request info in annotation (in my notes for the future, but lots to do) to help with this, but based on `origin: openSUSE:Leap:15.1:Update` it should be clear it is not coming from Factory. The pending request was https://build.opensuse.org/request/show/720651. Since we did not normally submit these pending requests automatically this was not a problem before, but will be going forward since it is harder to see given the origin does not yet have the sources in it. Given #2146 will keep the pending submissions disabled for now this should be less of an issue.
