### ISSUE TITLE
origin-manager: provide ability for cli to retrieve lookup file from operator

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/openSUSE-release-tools#2188]
This allows for using `list` and other "heavy" commands locally without waiting hours. Additionally, the report and update features can utilize this so there is essentially one central crawl on which all other components depend.

**Comment by crazyscientist** [comment]
> without waiting hours

If it was _only_ hours. I called `osc -A https://api.opensuse.org origin list -p openSUSE:Leap:15.2:Update` on 2020-12-04 8:47 CET. Now (3 days later) the command is not finished; also it's not doing anything anymore. According to `strace` it's stuck in a `read` operation.

**Comment by crazyscientist** [comment]
OK, at the fourth attempt (thanks to a view abortions due to HTTP 500 responses) I got a response in 15.5 hours.

However, I wrote a reference implementation of the `list` feature, which has only a runtime of a few minutes. I compared a sample of 300 results with the output of the original implementation. I found less than 20 packages, where the results were different. These differences are divided in two categories:

#. The original implementation does not follow an inheritance (e.g. if `SLE-15-SP2:Update` is identified as the origin of a package and it inherits from `SLE-15-SP2:GA`, it does not resolve this inheritance). 
#. In the other scenario, the ooriginal implementation identifies `openSUSE:Factory` as origin, despite the fact that requests from `SLE-15:*` exist. IMHO, this is the wrong result from the original implementation: https://github.com/openSUSE/openSUSE-release-tools/issues/2506.

If you are interested in my solution: https://github.com/crazyscientist/osc-tiny/pull/27

**Comment by coolo** [comment]
The origin manager really needs to be replaced with something simpler - taking that Leap is no longer moving in the way it was expected to move when 15.2 was done.

**Comment by coolo** [comment]
I don't think we need origin manager atm, so I'm closing this ticket. The only user is SLE release managers manually overriding any complaint coming from reviews.

https://github.com/openSUSE/openSUSE-release-tools/pull/2730
