### ISSUE TITLE
check_source: wrong declines submission if the package has linked to a maintenance update

### ISSUE THREAD

**Issue by nilxam** [openSUSE/openSUSE-release-tools#2294]
factory-auto declines submission if it is a maintenance update in a GA project, don't know why these rejection just happened.

    osc api /source/SUSE:SLE-15-SP2:GA/go1.11/_meta
    <package name="go1.11" project="SUSE:SLE-15:Update">
      <title/>
      <description/>
    </package>

    osc api /source/SUSE:SLE-15-SP2:GA/go1.11/_link
    <link package='go1.11.12318' cicount='copy' />

so go1.11 is a valid package update for 15.2, but got declined due to "May not modify a non-source package of type maintenance_update"
https://build.opensuse.org/request/show/745640

**Comment by jberry-suse** [comment]
Then likely need to expand to include `maintenance_update`?

**Comment by jberry-suse** [comment]
`factory-auto` is complaining about `package_kind('openSUSE:Leap:15.2', 'go1.11')` which is equal to `maintenance_update`. This is due to the following condition being met.

https://github.com/openSUSE/openSUSE-release-tools/blob/547e954a0b916d4360326a150f0fda076aa30617/osclib/core.py#L553-L554

Why does only that package have releasename set as normally that is reserved for maintenance updates (ie. with number suffix in package name)?

Either the meta for `openSUSE:Leap:15.2/go1.11` should be corrected or we need a more advanced method of detecting such packages in `package_kind()`.

**Comment by jberry-suse** [comment]
One can verify via:

```
$ osc api /source/openSUSE:Leap:15.2/go1.11/_meta
```

```xml
<package name="go1.11" project="openSUSE:Leap:15.2">
  <title/>
  <description/>
  <releasename>go1.11</releasename>
</package>
```

**Comment by jberry-suse** [comment]
Could potentially workaround this by making the condition check if value is different from package name. Still shouldn't be there I would expect.
