### ISSUE TITLE
repo_checker: delete: check install-time dependencies

### ISSUE THREAD

**Issue by plusky** [openSUSE/openSUSE-release-tools#277]
factory-repo-check.pl fails to check for recomended package which already casued issues when microcode_ctl was removed from factory - see: https://build.opensuse.org/request/show/265522

**Comment by jberry-suse** [comment]
Should be partially resolved by #964 as all packages withing a staging are checked so for ring packages and patterns this will work out of the box. I would expect the delete check should catch anything once extended to support runtime deps. Otherwise, the installcheck will pickup the issue, but will ignore it due to #980. As such it seems to make sense to change this issue to request runtime dep check for delete requests.

**Comment by jberry-suse** [comment]
Closed related https://progress.opensuse.org/issues/10814 as duplicate.

**Comment by DimStar77** [comment]
Was fixed by https://github.com/DimStar77/openSUSE-release-tools/commit/c676ba73845aa21cbb116dc3dce8db5708c11c4a
