### ISSUE TITLE
make factory announcer more generic

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#703]
the factory announcer needs to be reworked to
- support other architectures such as s390
- support other distributions like Leap
- maybe work on the ftp tree instead of DVD

**Comment by lnussel** [comment]
any news here?

**Comment by jberry-suse** [comment]
Will dig in on Monday.

**Comment by jberry-suse** [comment]
Seems like there are a couple of approaches and some assumptions I should verify before proceeding. To start of with, specific to the environment in which the code runs currently. Assumptions:

- has disk access to read DVD iso directly
- does not read directories containing rpms which code supports
- script is triggered as part of the publish process
  - this likely is not duplicated for s390x, but could be for Leap if not currently

Based on the desired features to support and looking over the commonalities between the output information for the three targets it seems the rpm tree is the only reliable source. The repodata file list cannot be used since it is not provided for Factory s390x. Reading from OBS directly could be a possibility, but would likely be fairly slow for this purpose and is not always in-sync with what is published, but that may be a problem regardless.

I have previous written a dashboard that displays package version across the Factory workflow:

- http://tumbleweed.boombatower.com/
- https://github.com/boombatower/opensuse-tumbleweed-dashboard

The dashboard access information both from HTTP download tree and OBS which is why it is clear when the publish to HTTP is out-of-sync.

Given that the output is a diff of the changelog all current and previous changelogs will need to be available to the script. Unless OBS revisions can be used as a source for this information, but given that revisions may be skipped the previous published revision will be required which may be tricky to obtain.

If the HTTP/FTP/rsync tree is used as source then the script will essentially need a full sync of the tree before it can operate. After that, either keep the previous versions of rpms around or cache the information of interest as is done now (via pickle serialization). The current form of serialization store the entire set of meta information for each package for every published snapshot (ie lots of duplicate information).

The tree sync was something I dealt with when trying to make snapshots of Tumbleweed and can really only be solved properly via rsync, but having an entire copy of the tree seems like a lot of excess if the real tree can be accessed.

I had considered and this may still be possible, diffing the file list and downloading the changed/new rpms at which point they could be diffed against the cached meta data if available. Assuming the snapshots are relatively small the about downloaded would not be overwelhming although likely regularly more than the ISO size.

Before the rysnc tree got all messed up I have the following snapshots and the disk size information as follows. The rsync tree was semi-stuck for one or two of the snapshots which makes the sizes bogus, but the numbers provide an idea of what would need to be downloaded.

```
129G	/srv/www/htdocs/snapshot/20161201/
3.2G	/srv/www/htdocs/snapshot/20161202/
3.7G	/srv/www/htdocs/snapshot/20161203/
13G	/srv/www/htdocs/snapshot/20161204/
7.2G	/srv/www/htdocs/snapshot/20161205/
353M	/srv/www/htdocs/snapshot/20161206/
1.4G	/srv/www/htdocs/snapshot/20161207/
3.0G	/srv/www/htdocs/snapshot/20161208/
3.0G	/srv/www/htdocs/snapshot/20161209/
22G	/srv/www/htdocs/snapshot/20161210/
2.2G	/srv/www/htdocs/snapshot/20161211/
16G	/srv/www/htdocs/snapshot/20161212/
2.2G	/srv/www/htdocs/snapshot/20161213/
14G	/srv/www/htdocs/snapshot/20161217/
```

This can be reduced if the source rpms are used directly instead of looking at the arch specific rpms and reading the sourcerpm header to normalize subpackages. The only issue with reading source rpms is that they do not appear to be present for Leap, but they are for s390x Factory and Tumblweweed. Given the duplication of downloading subpackages the required download size would be ruduced, but not easily predictable by how much. The reason for the concern is that gcc rebuilds would be near the full size of 130G (without ISOs).

If source rpms are used I am not sure the subpackages are easily parseable. Likely they are, but I would have to look at the details of the format. Currently, the changes output lists the subpackages, but that may not be that useful. Somewhat boils down to what folks are supposed to get from the output of the script.

If IT finishes deploying my snapshot script then proper snapshots will be kept of Tumbleweed which would make it easy to walk the tree and diff. In fact, simply list the files in current snapshot that are not hardlinks shared by previous snapshot and diff the changelogs of those files. No metadata or messing around. Obviously, snapshots would need to be kept of Leap and s390x to make that work and likely that will not happen.

I had toyed around with the idea of having a website that relates to snapshots to show the exact version of all packages availabe in that snapshot. Then folks could post in forums and such I am running Tumbleweed 20170101 and anyone trying to help would know what version of software they were running even if they view the post in the future. Obviously, having such a site could also provide a diff view that relates to this script.

Long-story short, seems like a couple factors that determine how to proceed:

- rsync/http download or direct access to rpm trees
- source rpms possible for Leap?

The most likely way forward, since it does not require direct access to rpm tree, is to cache data as currently being done.

- Compare file list, from HTTP call with xpath traversal, against the cache file list.
- Download files only found in current list.
- Deal with source rpm normalization in the same fashion as existing script.
- Diff current changelog from download rpm against cached changelog.

The tricky bit is that a full download will be necessary to initialize the cache and the cache will either need to be walked backwards to the last time the package was changed or duplicated by copying from previous snapshot when new snapshot cache is written. All of this is handled automatically by snapshot tool since hardlinks are used that alleviate copying and cleanup when bumped off the last snapshot kept.

The one issue with this approach is likely to be the same as making snapshots of Tumbleweed. When a new snapshot is published it is not instantly synced to HTTP or rysnc trees and as such not all new rpms will be available. Looking at repodata would solve that since one could wait until all files in list were published, but not available for s390x and still rather ugly.

I prototyped out some of the initial bits for this approach, but seems like I should confirm it before proceeding.

Downloading the DVD ISO simplified things in a lot of ways.

- entire copy of all packages always available to write to cache
- no pre-diff and download new step
- no syncing issues, as once the DVD is available the script can run
- no source rpm consideration since arch specific on DVD

**Comment by lnussel** [comment]
Jimmy Berry wrote:
> Seems like there are a couple of approaches and some assumptions I
> should verify before proceeding. To start of with, specific to the
> environment in which the code runs currently. Assumptions:
>
> - has disk access to read DVD iso directly
> - does not read directories containing rpms which code supports
> - script is triggered as part of the publish process
>   - this likely is not duplicated for s390x, but could be for Leap if not currently

The script to dump and diff changelogs currently runs on the openqa
host. As such it has disk access to all ISOs and the full ftp tree.
Since openQA quite agressively cleans up old ISOs and trees the
script caches the information it needs itself.
The actual report is generated elsewhere by talking to the web api
and it ends up on download.opensuse.org. Finally the announcer polls
http://download.opensuse.org/tumbleweed/iso/ to determine when a new
snapshot is actually visible in order to send an email.

> [...]
> If source rpms are used I am not sure the subpackages are easily
> parseable. Likely they are, but I would have to look at the
> details of the format. Currently, the changes output lists the
> subpackages, but that may not be that useful. Somewhat boils down
> to what folks are supposed to get from the output of the script.

Source rpms do not contain subpackage information. If if they did
(or we'd parse the spec file in it) we still wouldn't know if the
subpackages actually end up getting published. So the script really
has to look at the actually published binary rpms.

The output format seems to be fine, at least I haven't heard
complaints since quite a while :-) So we can stick with that.
I had assumed that making the announcer a bit more generic doesn't
require a full rewrite or changing the design. You seem to be aiming
higher though. Do you have a bigger picture in mind?

> Long-story short, seems like a couple factors that determine how to proceed:
>
> - rsync/http download or direct access to rpm trees

Direct access.

> - source rpms possible for Leap?

Yes. They are not synced to openQA atm but we could do it. I don't
think src rpms help us though.

cu
Ludwig

-- 
  (o_   Ludwig Nussel
  //\
  V_/_  http://www.suse.com/
SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard,
Graham Norton, HRB 21284 (AG Nürnberg)

**Comment by jberry-suse** [comment]
Is there a desire for knowing the subpackages?. Seems like the goal is to get an overview of what changed which is the major package name (normalized to source package already) and print new change entries. Is printing the kernel-* list useful? Using source rpms alleviates the need for the kernel trickery to hide packages (which I imagine does not work for other similar package setups which may be especially important if this is expanded beyond the DVD).

Overall, seems like the the majority of what is left is setup work on openqa box. I'll add a commit tweak `announcer.py` to parameterize some of the text strings.

Lastly, the web interface likely can just be duplicated at another path for each project.

**Comment by jberry-suse** [comment]
Will s390x ever have the same sort of iso setup as TW? Presumably Leap will during pre-release? The announcer.py script needs a data source for the current version that isn't looking for redirect from current ISO. Perhaps it could just query the openqa web as it should run last?

**Comment by lnussel** [comment]
querying openQA doesn't work as there is a delay until stuff appears on download.opensuse.org, so we have to query the download server
You may try media.1/build

**Comment by jberry-suse** [comment]
`media.1/{build|products}` would work, but that needs to be exposed for s390x which at the moment does not appear to be unless pulled directly from OBS.

**Comment by lnussel** [comment]
http://download.opensuse.org/ports/zsystems/tumbleweed/repo/oss/media.1/build

**Comment by jberry-suse** [comment]
hehe, alright need to stop looking at that other tree. I'll go ahead and change the announcer to use this.

**Comment by jberry-suse** [comment]
I've modified the announcer, to read build info from repo, but also need to handle creation of new openqa URL which has 3 arguments that need changing and only one is already available. Rather than add a load of parameters to the script (for where to look for build info, subject string etc) it would seem to be better to go back to creating a profile config like I was doing originally. On that note, I was thinking about scanning the repo trees instead of just ISO again (storing what to scan in the config) and remembered the source rpm vs arch specific discussion.

I do not believe we ever covered whether the list of subpackages was useful? You noted that without it the script cannot tell if the subpackages were published, but unless humans are interested in that the script is not used to validate what was published. Seems more like the overview of changes is useful rather than the subpackages. If should simplify things and reduce the total data processed and stored by just looking at the source rpms.

**Comment by lnussel** [comment]
The kernel hack would still be necessary as the kernel-source src rpm builds the kernel-source binary rpms, all other kernel binary packages have their own (no)src rpm. Also, the src rpms are not synced to openQA. Not a big deal to implement but needs to be done and it would be somehow wasteful as we don't need the source rpms for anything else (unless we get an openqa test that tries to install sources).
Alternative would be to run the changelog extractor directly on download.o.o. I can give you access if you want to evaluate that possibility. We'd have to talk to infra if we really install something there though.

**Comment by okurz** [comment]
actually we do have sources more and more in openQA tests, e.g. for "zypper info on source packages" test -> https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2596 and similar for debug packages -> https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/2649

**Comment by jberry-suse** [comment]
I am not totally familiar with all the pieces in to play, but if using src rpms is agreeable and they are not needed on openqa then your suggestion of running d.o.o seems reasonable. I imagine a different technique will be needed for determining the version represented and/or when to trigger. Can you point me to the bits responsible for publishing a snapshot to Tumbleweed main after passing openqa?

**Comment by jberry-suse** [comment]
Deployed to `openqa` machine while leaving Factory workflow alone.

- https://openqa.opensuse.org/factory-package-news/
- https://openqa.opensuse.org/snapshot-changes/opensuse/42.3/

The Factory one should be changed to the following once the pontifex changes are complete. @lnussel 

- https://openqa.opensuse.org/snapshot-changes/opensuse/tumbleweed

Summary:

- cloned `osc-plugin-factory` into `/var/lib/openqa/osc-plugin-factory-new` to leave existing alone
- created `/var/lib/snapshot-changes/opensuse/` directory
- symlinked existing factory path into it as `tumbleweed` to keep `rsync.pl` changes happy
- confirmed appropriate user can still write to directory through symlink
- created `/var/lib/snapshot-changes/opensuse/42.3` directory and `chown` to appropriate user
- `/etc/apache2/conf.d/factory-package-news.conf`
  - added second `WSGIScriptAlias` for `/snapshot-changes/opensuse/42.3` pointing to `-new` repo
  - added `Directory` entry
- updated `/etc/apache2/vhosts.d/openqa.conf` to include `ProxyPass /snapshot-changes !`
- pushed `rsync.pl` commit to `openqa-internal` repo
- pulled `openqa-internal` in deployed location (`/opt/openqa-scripts/`)
- reloaded `apache` service

The Factory web is still functional at old URL and we'll see if `rsync.pl` remains happy.

**Comment by jberry-suse** [comment]
Seems to have as `0175` was just push to openqa and 31M of snapshot data was generated.

**Comment by lnussel** [comment]
download.o.o done. changes files are in  /srv/www-local/snapshot-changes.  alias installed. waiting for next snapshot to see if it works :)

**Comment by jberry-suse** [comment]
It seems the first changes file was published with the snapshot published today: http://download.opensuse.org/distribution/leap/42.3/iso/Changes.0184.txt. Presumably the email announcer will function if enabled, but not sure at what list it should be pointed.

**Comment by jberry-suse** [comment]
`current` was never updated, perhaps not setup yet? Still shows `0174`.

**Comment by lnussel** [comment]
works fine now so far AFAICT

**Comment by jberry-suse** [comment]
The announcement emails have been hitting Factory so this all seems completed from the Leap standpoint. Do we want to go ahead and change up the Tumbleweed deployment to utilize your pontifex changes and redeploy tumbleweed bits of the same codebase and Leap or hold off?

**Comment by jberry-suse** [comment]
Was the factory announcer ever ported to the new setup on pontifex or is that somehting that still needs to be done?

**Comment by lnussel** [comment]
so what is missing is to finish the openqa side of the deployment

**Comment by jberry-suse** [comment]
Factory needs to be redeployed on pontifex to match Leap setup and then the openqa side can be redeployed using latest code to match Leap.

**Comment by coolo** [comment]
this kind of works now - there is a lot of room for improvements on this whole setup, but IMO this ticket is done (as we have Leap announcements)
