### ISSUE TITLE
Staging bot 'wasted' a bootstrap chance

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#923]
Today, I accepted staging :B (contained perl) - then let the bot handle the filling up of the stagings.

To my surprise, the bot chose to put 
```
devel
devel:languages:ruby:extensions
```

in there, instead of giving the various wating ring-0 packages a priority pass on :B - considering that there are much more chances to find a staging space for ruby extensions than for ring0 (those often tend to be blocked a while - just look at :C for gcc7) it would probably be good if the bot could give ring0 packages priority if there is a staging available that CAN be used for ring0 packages (for TW that currently means A, B and C, of which only B and C are under the bots control)

**Comment by jberry-suse** [comment]
The bot is aware of bootstrapped stagings and gives strategies requiring bootstrapping priority. In this case there were no interesting strategies that included the bootstrapped packages. Two possibilities: 1) create a bootstrapped only strategy or move none+bootstrapped priority above others, 2) block staging strategies that do not require bootstrapping in such stagings.

**Comment by jberry-suse** [comment]
The reasoning being that both types of none strategies are evaluated last since they are the lowest priority. The end result being that if a strategy containing packages requiring bootstrapping is generated before all staging are filled it will always be given priority to bootstrapped staging. The balance being between waiting to fill a staging vs filling a bootstrapped staging with something not requiring bootstrapping.

If none+bootstrapped is evaluated first then a single package requiring bootstrapping will always be staged in the bootstrapped stagings over everything else or better grouping strategies. Perhaps a strategy similar to devel that is basically a none strategy that is only desirable if >= 7 (or some number) of packages match (likely not too different from devel=Base:System). Alternatively something based on the request age so that a bootstrapped staging is not occupied by a single package over another better group, but not infinitely left to languish.

It looks like in this case 5 packages from Base:System. Perhaps just adding another lower min like YaST:HEAD, but for Base:System. It really depends on what is desired, any of these solutions (and others) are relatively simple to implement.

**Comment by jberry-suse** [comment]
Doesn't seem like this is a reoccurring concern especially after adding more stagings. Please re-open if that is incorrect.
